/**
 * Public storefront catalog. Tebex package IDs live in server.js because they are
 * delivery infrastructure, not product copy. Keep product ids stable.
 */
export const storeCatalog = {
  updatedAt: '2026-09-15',
  currency: 'CLP',
  payment: {
    mode: 'tebex',
    discord: 'https://discord.gg/rv3vtXZTk7',
    checkout: 'https://pay.tebex.io'
  },
  categories: [
    { id: 'monthly', label: 'Pases VIP', tagline: 'Pases manuales de 30 días, sin renovación automática. Progresión griega real, utilidades y auras integradas por Odysseia.' },
    { id: 'titans', label: 'Titanes Primordiales', tagline: 'La línea superior de rangos mensuales: equipo, protecciones y habilidades de escala primordial.' },
    { id: 'roles', label: 'Roles de Juego', tagline: 'Pases manuales de 30 días, sin renovación automática. Subrangos con identidad propia dentro de la comunidad.' },
    { id: 'kits', label: 'Kits y equipo', tagline: 'Resumen de lo que trae cada línea de rango.' },
    { id: 'protection', label: 'Protecciones', tagline: 'Territorio VIP para bases, gremios y proyectos.' },
    { id: 'utility', label: 'Utilidad', tagline: 'Dragmas de plata y beneficios de economía.' },
    { id: 'slimefun', label: 'Conocimiento Slimefun', tagline: 'Desbloqueos permanentes de investigación sin entregar objetos ni permisos de administración.' }
  ],
  products: [
    { id: 'hercules', category: 'monthly', tier: 1, name: 'Hércules', badge: 'Entrada VIP', clp: 4990, usd: 4.99, featured: false, accent: 'bronze', summary: 'El punto de partida VIP: 3 bóvedas privadas portátiles, protección anti-robo 49x49 y aura de combate Odysseia.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Hércules', '📦 3 Bóvedas Virtuales Privadas (<code>/pv 1-3</code>) portátiles y seguras en cualquier mundo', '🛡️ Hito Hércules 49x49 con Blindaje Anti-Robo de cofres, máquinas Slimefun y redes de Networks', '3 homes, 5 warps de jugador (<code>/pw</code>) y hasta 20 tiendas QuickShop', 'Kit Hércules automático: set de diamante, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de diamante: Velocidad I + Resistencia I', 'Entrega automática del kit Hércules, 1 Hito PS y $35.000 ₯ en Dragmas'] },
    { id: 'hestia', category: 'monthly', tier: 2, name: 'Hestia', badge: 'Social', clp: 7990, usd: 7.99, featured: false, accent: 'rose', summary: 'Comodidad social y supervivencia extrema: 4 bóvedas privadas, sustentación en lava y territorio protegido 81x81.', includes: ['Pase manual de 30 días, sin renovación automática, hereda Hércules y suma Hito VIP Hestia', '📦 4 Bóvedas Virtuales Privadas (<code>/pv 1-4</code>) portátiles y seguras', '🛡️ Hito Hestia 81x81 con Blindaje Anti-Robo de cofres, máquinas Slimefun y redes de Networks', '5 homes, <code>/nick</code>, <code>/ptime</code>, <code>/pweather</code>, <code>/ext</code> y hasta 30 tiendas QuickShop', 'Kit Hestia automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🔥 Caminar en Lava (sustentación sobre lagos de lava, inmunidad al fuego y estela de llamas sagradas)', 'Aura de armadura Odysseia: Velocidad II + Health Boost I + Saturación', 'Entrega automática del kit Hestia, 1 Hito PS y $75.000 ₯ en Dragmas'] },
    { id: 'hermes', category: 'monthly', tier: 3, name: 'Hermes', badge: 'Vuelo /fly', clp: 10990, usd: 10.99, featured: true, accent: 'violet', summary: '¡El rango más codiciado! Vuelo permanente <code>/fly</code> ilimitado en todo el Survival (¡sin baterías ni gemas!), 5 bóvedas privadas y movilidad suprema.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Hermes', '🪽 ¡Vuelo Permanente <code>/fly</code> libre e ilimitado en todo el Survival! Olvídate de recargar energía o perder gemas', '📦 5 Bóvedas Virtuales Privadas (<code>/pv 1-5</code>) portátiles y 100% seguras anti-robo', '🛡️ Hito Hermes 113x113 con Blindaje Anti-Robo de máquinas Slimefun y redes de Networks', '6 homes, 8 warps, <code>/speed</code>, <code>/back</code>, <code>/workbench</code>, <code>/enderchest</code>, <code>/compass</code>, RTP instantáneo y hasta 40 tiendas QuickShop', 'Kit Hermes automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🪽 Paso Ligero del Viento (estela de nubes, salto alado y sin romper cultivos)', 'Aura de armadura Odysseia: Velocidad IV + Health Boost I + Saturación', 'Entrega automática del kit Hermes, 1 Hito PS y $150.000 ₯ en Dragmas'] },
    { id: 'hefesto', category: 'monthly', tier: 4, name: 'Hefesto', badge: 'Técnico', clp: 15990, usd: 15.99, featured: false, accent: 'ember', summary: 'El paraíso de los jugadores técnicos: vuelo ilimitado <code>/fly</code>, 7 bóvedas privadas y todas las estaciones de trabajo virtuales.', includes: ['Pase manual de 30 días, hereda vuelo <code>/fly</code> permanente y suma Hito VIP Hefesto', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 7 Bóvedas Virtuales Privadas (<code>/pv 1-7</code>) para almacenar componentes y maquinaria Slimefun', '🛡️ Hito Hefesto 177x177 con Blindaje Anti-Robo de máquinas Slimefun, reactores y redes de Networks', '8 homes, 8 warps, estaciones virtuales completas (<code>/anvil</code>, <code>/grindstone</code>, <code>/smithingtable</code>, <code>/stonecutter</code>, <code>/condense</code>, <code>/feed</code>) y hasta 50 tiendas', 'Kit Hefesto automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🔨 Paso Ígneo de la Forja (caminar en lava sin quemarse + forja virtual)', 'Aura de armadura Odysseia: Velocidad II + Health Boost II + Resistencia al Fuego + Saturación', 'Entrega automática del kit Hefesto, 1 Hito PS y $250.000 ₯ en Dragmas'] },
    { id: 'artemisa', category: 'monthly', tier: 5, name: 'Artemisa', badge: 'Exploración', clp: 22990, usd: 22.99, featured: false, accent: 'cyan', summary: 'Verticalidad y caza superior: vuelo ilimitado <code>/fly</code>, 8 bóvedas privadas, conservación total de EXP al morir y claim masivo.', includes: ['Pase manual de 30 días, hereda vuelo <code>/fly</code> permanente y suma Hito VIP Artemisa', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '✨ Conservación del 100% de Experiencia (EXP) al morir en cualquier dimensión', '📦 8 Bóvedas Virtuales Privadas (<code>/pv 1-8</code>) seguras y portátiles', '🛡️ Hito Artemisa 241x241 con Blindaje Anti-Robo de cofres, máquinas Slimefun y redes de Networks', '10 homes, 12 warps de jugador, <code>/jump</code>, <code>/top</code> y hasta 60 tiendas QuickShop', 'Kit Artemisa automático: set de netherita, arco, herramientas y consumibles', 'Aura de armadura Odysseia: Velocidad III + Health Boost II + Fuerza I + Saturación', 'Entrega automática del kit Artemisa, 1 Hito PS y $450.000 ₯ en Dragmas'] },
    { id: 'afrodita', category: 'monthly', tier: 6, name: 'Afrodita', badge: 'Comercio Élite', clp: 31990, usd: 31.99, featured: false, accent: 'pink', summary: 'El imperio comercial del servidor: 0% comisión en QuickShop (+15% rentabilidad neta), 10 bóvedas privadas, /repair y territorio de 353x353.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Afrodita', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '🪙 0% Impuestos y comisiones en QuickShop (+15% de rentabilidad neta directa en tus ventas)', '📦 10 Bóvedas Virtuales Privadas (<code>/pv 1-10</code>) portátiles y seguras', '🛡️ Hito Afrodita 353x353 con Blindaje Anti-Robo de máquinas Slimefun y redes de Networks', '12 homes, 15 warps, <code>/repair</code>, <code>/sell</code> y hasta 70 tiendas QuickShop', 'Kit Afrodita automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 💖 Gracia Marina (caminar sobre el agua + Dolphin\'s Grace)', 'Aura de armadura Odysseia: Velocidad III + Health Boost III + Fuerza I + Regeneración I + Saturación', 'Entrega automática del kit Afrodita, 1 Hito PS y $700.000 ₯ en Dragmas'] },
    { id: 'zeus', category: 'monthly', tier: 7, name: 'Zeus', badge: 'Rango Supremo', clp: 44990, usd: 44.99, featured: true, accent: 'gold', summary: 'La cima absoluta del Olimpo: Keep Inventory permanente (nunca pierdes tus ítems al morir), vuelo /fly, 15 bóvedas privadas y /repair all.', includes: ['Pase manual de 30 días con herencia total y vuelo <code>/fly</code> permanente', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival sin requerir ítems ni energía', '⚡ Keep Inventory Permanente: ¡Conserva todo tu inventario y equipamiento al morir en cualquier mundo!', '📦 15 Bóvedas Virtuales Privadas (<code>/pv 1-15</code>) para almacenamiento masivo e indestructible', '🛡️ Hito Zeus 481x481 con Blindaje Anti-Robo Absoluto para megacomplejos de Networks y Slimefun', '🪙 Máximo Beneficio Comercial QuickShop: 0% impuestos de venta (+30% de rentabilidad económica)', '20 homes, 25 warps, <code>/repair all</code>, <code>/heal</code>, <code>/near</code> y hasta 80 tiendas QuickShop', 'Kit Zeus automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: ⚡ Paso del Trueno (estelas de chispas eléctricas, velocidad y gracia divina)', 'Aura de armadura Odysseia: Velocidad IV + Health Boost IV + Fuerza II + Resistencia I + Saturación', 'Entrega automática del kit Zeus, 1 Hito PS y $1.500.000 ₯ en Dragmas'] },

    { id: 'thor', category: 'monthly', tier: 8, name: 'Thor', badge: 'Panteón Nórdico', clp: 49990, usd: 49.99, featured: false, accent: 'gold', purchaseAvailable: true, summary: 'Panteón nórdico: vuelo ilimitado <code>/fly</code>, 20 bóvedas privadas, martillo Mjolnir bumerán y el Santuario del Trueno.', includes: ['Pase manual de 30 días, sin renovación automática con herencia total', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 20 Bóvedas Virtuales Privadas (<code>/pv 1-20</code>) portátiles y seguras', '🛡️ Hito Thor 601x601 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Trueno del Norte: <code>thunder IV</code> y <code>rage III</code> en las armas', 'Habilidad de arma con clic derecho: Martillo Mjolnir bumerán que impacta y regresa', 'Isla de 280×280 en SkyBlock y OneBlock, se aplica al reconectar', '2.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'anubis', category: 'monthly', tier: 9, name: 'Anubis', badge: 'Panteón Egipcio', clp: 54990, usd: 54.99, featured: false, accent: 'violet', purchaseAvailable: true, summary: 'Panteón egipcio: vuelo ilimitado <code>/fly</code>, 25 bóvedas privadas, robo de vida necrótico e invocación de espectros.', includes: ['Pase manual de 30 días, sin renovación automática con herencia total', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 25 Bóvedas Virtuales Privadas (<code>/pv 1-25</code>) portátiles y seguras', '🛡️ Hito Anubis 721x721 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Juicio del Desierto: <code>vampire IV</code>, <code>wither III</code> y <code>decapitator III</code>', 'Habilidad de arma con clic derecho: Robo de vida necrótico e invocación de espectros', 'Isla de 310×310 en SkyBlock y OneBlock, se aplica al reconectar', '2.500.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'poseidon', category: 'monthly', tier: 10, name: 'Poseidón', badge: 'Panteón Marino', clp: 59990, usd: 59.99, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Panteón marino: vuelo ilimitado <code>/fly</code>, 30 bóvedas privadas, caminar sobre aguas e impulso acuático abisal.', includes: ['Pase manual de 30 días, sin renovación automática con herencia total', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 30 Bóvedas Virtuales Privadas (<code>/pv 1-30</code>) portátiles y seguras', '🛡️ Hito Poseidón 841x841 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Habilidad de Armadura: 🌊 Caminar en Agua (correr sobre océanos y ríos sin hundirse, Dolphin\'s Grace y estelas de agua)', 'Marea Abisal: <code>ice_aspect IV</code> y <code>cold_steel III</code>', 'Habilidad de arma con clic derecho: Impulso acuático abisal', 'Isla de 340×340 en SkyBlock y OneBlock, se aplica al reconectar', '3.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-japeto', category: 'titans', tier: 11, name: 'Titán Japeto', badge: '5x Favor Divino', clp: 49990, usd: 49.99, featured: false, accent: 'ember', purchaseAvailable: true, summary: 'El primer Titán Primordial: 35 bóvedas privadas, vuelo <code>/fly</code>, Forja Primordial y multiplicador ×5 de favor divino.', includes: ['Pase mensual de 30 días, sin renovación automática', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 35 Bóvedas Virtuales Privadas (<code>/pv 1-35</code>) portátiles y seguras', '🛡️ Hito Japeto 1001x1001 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Forja Primordial: <code>veinminer IV</code>, <code>blast_mining IV</code>, <code>smelter III</code>', 'Habilidad de arma con clic derecho: multiplicador ×5 de favor divino', 'Isla de 400×400 en SkyBlock y OneBlock, se aplica al reconectar', '4.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-oceanus', category: 'titans', tier: 12, name: 'Titán Oceanus', badge: 'Vórtice Abisal', clp: 59990, usd: 59.99, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Titán de las profundidades: 40 bóvedas privadas, vuelo <code>/fly</code>, caminar sobre aguas y Vórtice Abisal que atrae hordas.', includes: ['Pase mensual de 30 días, sin renovación automática', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 40 Bóvedas Virtuales Privadas (<code>/pv 1-40</code>) portátiles y seguras', '🛡️ Hito Oceanus 1301x1301 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Habilidad de Armadura: 🌊 Caminar en Agua (correr sobre océanos y lagos sin hundirse con estelas abisales)', 'Corriente Eterna: <code>silk_chest</code>, <code>thrifty IV</code>, <code>veinminer V</code>', 'Habilidad de arma con clic derecho: Vórtice Abisal que atrae a las hordas al centro', 'Isla de 450×450 en SkyBlock y OneBlock, se aplica al reconectar', '5.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-hiperion', category: 'titans', tier: 13, name: 'Titán Hiperión', badge: 'Rayo Solar', clp: 69990, usd: 69.99, featured: false, accent: 'gold', purchaseAvailable: true, summary: 'Titán de la luz solar: 45 bóvedas privadas, vuelo <code>/fly</code>, rayo solar destructor y regeneración bajo el sol.', includes: ['Pase mensual de 30 días, sin renovación automática', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 45 Bóvedas Virtuales Privadas (<code>/pv 1-45</code>) portátiles y seguras', '🛡️ Hito Hiperión 1601x1601 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Luz Primera: <code>infernus V</code>, <code>fire_shield V</code>, <code>haste VI</code>', 'Habilidad de arma con clic derecho: rayo solar y regeneración bajo el sol', 'Isla de 500×500 en SkyBlock y OneBlock, se aplica al reconectar', '6.500.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-cronos', category: 'titans', tier: 14, name: 'Titán Cronos', badge: 'Parada Temporal', clp: 79990, usd: 79.99, featured: false, accent: 'violet', purchaseAvailable: true, summary: 'Titán del tiempo: 50 bóvedas privadas, vuelo <code>/fly</code>, Parada del Tiempo que congela a los enemigos y claim 2001x2001.', includes: ['Pase mensual de 30 días, sin renovación automática', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 50 Bóvedas Virtuales Privadas (<code>/pv 1-50</code>) portátiles y seguras', '🛡️ Hito Cronos 2001x2001 con Blindaje Anti-Robo de Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Señor del Tiempo: <code>paralyze V</code>, <code>stopping_force V</code>, <code>exhaust IV</code>', 'Habilidad de arma con clic derecho: Parada del Tiempo que inmoviliza a los enemigos', 'Isla de 550×550 en SkyBlock y OneBlock, se aplica al reconectar', '8.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-caos', category: 'titans', tier: 15, name: 'Titán Caos', badge: 'Rango máximo', clp: 89990, usd: 89.99, featured: true, accent: 'rose', purchaseAvailable: true, summary: 'La cima absoluta: 50 bóvedas privadas, vuelo <code>/fly</code>, set primordial, dominio temporal del vacío y protección máxima.', includes: ['Pase mensual de 30 días, sin renovación automática', '🪽 Vuelo Permanente <code>/fly</code> ilimitado en todo el Survival', '📦 50 Bóvedas Virtuales Privadas (<code>/pv 1-50</code>) portátiles y seguras', '🛡️ Hito Caos 2501x2501 con Blindaje Anti-Robo Absoluto de máquinas Slimefun y Networks', 'Kit completo de netherita irrompible y soulbound con trim Silence de amatista', 'Origen sin Forma distribuido en todo el set y sus armas: <code>hardened X</code>, defensas elementales VI, <code>vampire VI</code>, <code>thunder VI</code>, <code>infernus VI</code> y <code>paralyze VI</code>', 'Habilidad de arma con clic derecho: Espada Voladora Autónoma que persigue y ataca sola', '<code>/ultragod</code> personal: invulnerabilidad absoluta durante 45 segundos, con 30 minutos de recarga persistente', 'Isla de 600×600 en SkyBlock y OneBlock, se aplica al reconectar', '10.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'minero', category: 'roles', tier: 3, name: 'Rol: Minero', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'bronze', summary: 'Arranque técnico para minería masiva: pico Fortuna III, herramientas y suministros esenciales.', includes: ['Prefijo secundario [⛏ MINERO] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', 'Kit único: pico Fortuna III, pala, antorchas, escaleras y comida', 'El kit se entrega al comprar; no se repite con /kit', 'No incluye vuelo ni materiales de endgame'] },
    { id: 'cazador', category: 'roles', tier: 3, name: 'Rol: Cazador', badge: '30 días + PvE', clp: 2990, usd: 2.99, featured: false, accent: 'rose', summary: 'Equipo PvE de combate: armadura de diamante Protección IV, espada Sharpness V y arco Power IV.', includes: ['Prefijo secundario [⚔ CAZADOR] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', 'Kit único: armadura de diamante Protección IV', 'Espada Sharpness V, arco Power IV, flechas y manzanas doradas', 'No incluye netherita, elytra ni ítems Slimefun'] },
    { id: 'constructor', category: 'roles', tier: 3, name: 'Rol: Constructor', badge: '7 Días /fly', clp: 2990, usd: 2.99, featured: false, accent: 'violet', summary: '¡Ideal para proyectos grandes! 7 días de vuelo creativo libre, 576 bloques de construcción y andamios.', includes: ['Prefijo secundario [⚒ CONSTRUCTOR] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', '7 días exactos de VUELO LIBRE desde la compra para construir a cualquier altura', 'Kit único: 576 bloques de construcción, andamios y hacha', 'No incluye WorldEdit ni permisos de staff'] },
    { id: 'lenador', category: 'roles', tier: 3, name: 'Rol: Leñador', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'ember', summary: 'Potencia forestal: hacha Eficiencia V, tijeras, comida y 128 retoños para abastecer madera.', includes: ['Prefijo secundario [🪓 LEÑADOR] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', 'Kit único: hacha Eficiencia V, tijeras y comida', '64 retoños de roble, 64 de abeto y harina de hueso', 'No incluye fly ni automatización de árboles'] },
    { id: 'alquimista', category: 'roles', tier: 3, name: 'Rol: Alquimista', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'cyan', summary: 'Laboratorio de pociones listo: soporte, verrugas, polvo de blaze y 64 frascos para destilar.', includes: ['Prefijo secundario [🧪 ALQUIMISTA] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', 'Soporte de pociones, verrugas, polvo de blaze y 64 frascos', 'Ingredientes básicos para extender y potenciar pociones', 'No incluye brebajes de endgame ni ítems Slimefun'] },
    { id: 'nomada', category: 'roles', tier: 3, name: 'Rol: Nómada', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'pink', summary: 'Supervivencia y exploración veloz: botas de diamante, brújula, perlas de ender y cohetes.', includes: ['Prefijo secundario [⛺ NÓMADA] y rango por 30 días', '15.000 ₯ en Dragmas de bienvenida y 4 homes (<code>/sethome</code>) mientras dure el rol', 'Botas de diamante, brújula, cama, perlas y cohetes', 'Kit único entregado al comprar', 'No incluye elytra ni teletransporte de staff'] },

    { id: 'kit-hermes', category: 'kits', tier: 3, name: 'Kit Hermes', badge: 'Movilidad Élite', clp: 5990, usd: 5.99, featured: true, accent: 'violet', summary: 'Equipo de netherita de Hermes reforzado, herramientas soulbound, tótems y provisiones.', includes: ['Set de netherita Hermes con herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '16 manzanas doradas, 16 perlas de ender y 3 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'kit-zeus', category: 'kits', tier: 7, name: 'Kit Zeus', badge: 'Arsenal Mítico', clp: 14990, usd: 14.99, featured: true, accent: 'gold', summary: 'El kit de combate supremo: netherita mítica de Zeus, 8 tótems de inmortalidad y provisiones masivas.', includes: ['Set de netherita Zeus, herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '64 manzanas doradas, 64 perlas de ender y 8 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'protection-177', category: 'protection', tier: 4, name: 'Protección 177x177', badge: 'Base Industrial', clp: 3990, usd: 3.99, featured: false, accent: 'ember', summary: 'Hito de ProtecciónStones de 177x177 para bases, almacenes y fábricas industriales.', includes: ['Un Hito VIP Hefesto con área final de 177x177 bloques', 'Entrega automática al conectarte, con espacio libre en inventario', 'Pensada para farms y almacenes técnicos', 'No añade un rango VIP ni aumenta el límite de regiones'] },
    { id: 'protection-nether-colossus', category: 'protection', tier: 8, name: 'Coloso del Nether 501x501', badge: 'Nether 501x501', clp: 19990, usd: 19.99, featured: false, accent: 'ember', summary: 'Territorio masivo dentro del Nether, para bases y complejos industriales completos.', includes: ['Un Hito de proteccion de 501x501 bloques en el Nether', 'Entrega automatica al conectarte, con espacio libre en inventario', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-end-colossus', category: 'protection', tier: 8, name: 'Coloso del End 501x501', badge: 'The End 501x501', clp: 24990, usd: 24.99, featured: false, accent: 'violet', summary: 'Territorio masivo dentro del End, pensado para granjas de gran escala.', includes: ['Un Hito de proteccion de 501x501 bloques en el End', 'Entrega automatica al conectarte, con espacio libre en inventario', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-atlas', category: 'protection', tier: 9, name: 'Dominio de Atlas 1001x1001', badge: '1 Km² (Supremo)', clp: 49990, usd: 49.99, featured: true, accent: 'gold', summary: 'La proteccion mas grande del servidor: un kilometro cuadrado para ciudades y gremios.', includes: ['Un Hito de proteccion de 1001x1001 bloques en el Overworld', 'Entrega automatica al conectarte, con espacio libre en inventario', 'Ideal para proyectos comunitarios y gremios completos', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-481', category: 'protection', tier: 7, name: 'Protección 481x481', badge: 'Mega Proyecto', clp: 11990, usd: 11.99, featured: true, accent: 'gold', summary: 'Hito VIP Zeus de 481x481 bloques para ciudades, granjas y proyectos grandes.', includes: ['Un Hito VIP Zeus con área final de 481x481 bloques', 'Entrega automática mediante Odysseia al conectarte', 'Pensada para ciudades y complejos técnicos', 'No añade un rango VIP ni aumenta el límite de regiones'] },

    { id: 'utility-economy', category: 'utility', tier: 6, name: 'Economía Premium', badge: 'Permanente', clp: 6990, usd: 6.99, featured: false, accent: 'pink', summary: 'Beneficios comerciales permanentes: 25 tiendas, <code>/sell</code>, prefijo exclusivo y chat con color.', includes: ['Hasta 25 tiendas QuickShop (el jugador base tiene 10)', '<code>/sell</code> para vender directo al servidor sin montar tienda', 'Distinción permanente en el chat con prefijo [Economía Premium]', 'Formato de color y estilo en mensajes públicos', 'Compatible con cualquier rango VIP mensual o rol', 'Permanente: no caduca ni se renueva; no cambia los impuestos de QuickShop'] },
    { id: 'dragmas-saco', category: 'utility', tier: 3, name: 'Saco de Dragmas (50.000 ₯)', badge: 'Arranque (50k)', clp: 1990, usd: 1.99, featured: false, accent: 'bronze', summary: 'Un saco mediano de dragmas de plata para impulsar tu economía.', includes: ['50.000 Dragmas (₯) depositados en el juego', 'Comercio instantáneo en tiendas de jugadores', 'Ideal para compra de materias primas', 'Entrega automatizada vía comando o ticket'] },
    { id: 'dragmas-cofre', category: 'utility', tier: 5, name: 'Cofre de Dragmas (250.000 ₯)', badge: 'Popular (250k)', clp: 7990, usd: 7.99, featured: true, accent: 'violet', summary: 'Cofre robusto de dragmas para proyectos que necesitan capital inmediato.', includes: ['250.000 Dragmas (₯) depositados en el juego', 'Mayor capital para comprar claims o máquinas', 'Entrega automatizada vía Odysseia'] },
    { id: 'dragmas-anfora', category: 'utility', tier: 7, name: 'Ánfora de Dragmas (1.000.000 ₯)', badge: 'Magnate (1M)', clp: 24990, usd: 24.99, featured: true, accent: 'gold', summary: 'Capital para proyectos grandes, comercio pesado y compras de alto nivel.', includes: ['1.000.000 Dragmas (₯) depositados en el juego', 'Máximo poder adquisitivo en el servidor', 'Entrega automatizada vía Odysseia'] },
    { id: 'slimefun-research-all', category: 'slimefun', tier: 1, name: 'Conocimiento Total de Slimefun', badge: 'Permanente', clp: 9990, usd: 10.00, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Ahorra semanas de farmeo: desbloqueo permanente instantáneo de todas las investigaciones de Slimefun.', includes: ['Desbloqueo inmediato y permanente de todas las ramas de investigación de Slimefun', 'Acceso directo a recetas de maquinaria industrial, redes y magia en la guía', 'Ahorra miles de niveles de experiencia y semanas de farmeo previo', 'Entrega automática al conectarte al servidor con inventario libre'] },

  ]
};
