/**
 * Public storefront catalog. Tebex package IDs live in server.js because they are
 * delivery infrastructure, not product copy. Keep product ids stable.
 */
export const storeCatalog = {
  updatedAt: '2026-07-10',
  currency: 'CLP',
  payment: {
    mode: 'tebex',
    discord: 'https://discord.gg/rR7FbfCt9Y',
    checkout: 'https://pay.tebex.io'
  },
  categories: [
    { id: 'monthly', label: 'Pases VIP', tagline: 'Pases manuales de 30 días, sin renovación automática. Progresión griega real, utilidades y auras integradas por Odysseia.' },
    { id: 'roles', label: 'Roles de Juego', tagline: 'Pases manuales de 30 días, sin renovación automática. Subrangos con identidad propia dentro de la comunidad.' },
    { id: 'kits', label: 'Kits y equipo', tagline: 'Resumen de lo que trae cada línea de rango.' },
    { id: 'protection', label: 'Protecciones', tagline: 'Territorio VIP para bases, gremios y proyectos.' },
    { id: 'utility', label: 'Utilidad', tagline: 'Dragmas de plata y beneficios de economía.' },
    { id: 'custom', label: 'Pases especiales', tagline: 'Accesos temporales con checkout y activación gestionados por Tebex.' }
  ],
  products: [
    { id: 'hercules', category: 'monthly', tier: 1, name: 'Hércules', badge: 'Entrada VIP', clp: 4990, usd: 4.99, featured: false, accent: 'bronze', summary: 'El punto de partida VIP para entrar fuerte al survival sin romper el balance del servidor.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Hércules', 'Incluye 1 Hito Hércules para crear una protección de 49x49 bloques', '3 homes, 5 warps de jugador (/pw) y hasta 20 tiendas QuickShop', 'Kit Hércules automático: set de diamante, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de diamante: Velocidad I + Resistencia I', 'Entrega automática del kit Hércules, 1 Hito PS y $35.000 ₯ en Dragmas'] },
    { id: 'hestia', category: 'monthly', tier: 2, name: 'Hestia', badge: 'Social', clp: 7990, usd: 7.99, featured: false, accent: 'rose', summary: 'Comodidad social, mejor defensa y una economía temprana bastante más sólida.', includes: ['Pase manual de 30 días, sin renovación automática, hereda Hércules y suma Hito VIP Hestia', 'Incluye 1 Hito Hestia para crear una protección de 81x81 bloques', '5 homes, /nick, /ptime, /pweather, /ext y hasta 30 tiendas QuickShop', 'Kit Hestia automático: set, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de diamante: Velocidad II + Health Boost I + Saturación', 'Entrega automática del kit Hestia, 1 Hito PS y $75.000 ₯ en Dragmas'] },
    { id: 'hermes', category: 'monthly', tier: 3, name: 'Hermes', badge: 'Recomendado', clp: 10990, usd: 10.99, featured: true, accent: 'violet', summary: 'El rango recomendado para jugar survival intensivo con movilidad real y mucha calidad de vida.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Hermes', 'Incluye 1 Hito Hermes para crear una protección de 113x113 bloques', '6 homes, 8 warps, /fly, /speed, /back, /workbench, /enderchest, /compass, /wild y hasta 40 tiendas QuickShop', 'Kit Hermes automático: set de netherita, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de diamante: Velocidad IV + Health Boost I + Saturación', 'Entrega automática del kit Hermes, 1 Hito PS y $150.000 ₯ en Dragmas'] },
    { id: 'hefesto', category: 'monthly', tier: 4, name: 'Hefesto', badge: 'Técnico', clp: 15990, usd: 15.99, featured: false, accent: 'ember', summary: 'Pensado para granjas, minería pesada y jugadores técnicos que quieren herramientas reales.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Hefesto', 'Incluye 1 Hito Hefesto para crear una protección de 177x177 bloques', '8 homes, 8 warps, /feed, /condense, estaciones virtuales completas y hasta 50 tiendas QuickShop', 'Kit Hefesto automático: set de netherita, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de netherita: Velocidad II + Health Boost II + Resistencia al Fuego + Saturación', 'Entrega automática del kit Hefesto, 1 Hito PS y $250.000 ₯ en Dragmas'] },
    { id: 'artemisa', category: 'monthly', tier: 5, name: 'Artemisa', badge: 'Exploración', clp: 22990, usd: 22.99, featured: false, accent: 'cyan', summary: 'Verticalidad, daño a distancia y supervivencia de alto nivel para dominar mapas y combates largos.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Artemisa', 'Incluye 1 Hito Artemisa para crear una protección de 241x241 bloques', '10 homes, 12 warps de jugador, /jump, conservación de XP al morir y hasta 60 tiendas QuickShop', 'Kit Artemisa automático: set de netherita, arco, herramientas y consumibles', 'Aura de armadura Odysseia con set completo de netherita: Velocidad III + Health Boost II + Fuerza I + Saturación', 'Entrega automática del kit Artemisa, 1 Hito PS y $450.000 ₯ en Dragmas'] },
    { id: 'afrodita', category: 'monthly', tier: 6, name: 'Afrodita', badge: 'Economía', clp: 31990, usd: 31.99, featured: false, accent: 'pink', summary: 'El rango de comercio alto: acelera la economía y mantiene una presencia premium constante.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Afrodita', 'Incluye 1 Hito Afrodita para crear una protección de 353x353 bloques', '12 homes, 15 warps, /repair, /sell y hasta 70 tiendas QuickShop', 'Kit Afrodita automático: set de netherita, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de netherita: Velocidad III + Health Boost III + Fuerza I + Regeneración I + Saturación', 'Entrega automática del kit Afrodita, 1 Hito PS y $700.000 ₯ en Dragmas'] },
    { id: 'zeus', category: 'monthly', tier: 7, name: 'Zeus', badge: 'Rango top', clp: 44990, usd: 44.99, featured: true, accent: 'gold', summary: 'La cima del Olimpo: utilidades máximas, aura más fuerte y el kit más alto que hoy existe en DrakesCraft.', includes: ['Pase manual de 30 días, sin renovación automática y herencia total de la línea VIP anterior', 'Incluye 1 Hito Zeus para crear una protección de 481x481 bloques', '20 homes, 25 warps, /repair all, /heal, /near, keep inventory y hasta 80 tiendas QuickShop', 'Kit Zeus automático: set de netherita, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de netherita: Velocidad IV + Health Boost IV + Fuerza II + Resistencia I + Saturación', 'Entrega automática del kit Zeus, 1 Hito PS y $1.500.000 ₯ en Dragmas'] },

    { id: 'minero', category: 'roles', tier: 3, name: 'Rol: Minero', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'bronze', summary: 'Rango temporal para quienes quieren identificarse como Minero dentro de la comunidad.', includes: ['Prefijo secundario [⛏ MINERO] en el chat', 'Rango Minero por 30 días', 'Acceso al permiso interno del rol Minero', 'No incluye kit ni ítems automáticos'] },
    { id: 'cazador', category: 'roles', tier: 3, name: 'Rol: Cazador', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'rose', summary: 'Rango temporal para quienes quieren identificarse como Cazador dentro de la comunidad.', includes: ['Prefijo secundario [⚔ CAZADOR] en el chat', 'Rango Cazador por 30 días', 'Acceso al permiso interno del rol Cazador', 'No incluye kit ni ítems automáticos'] },
    { id: 'constructor', category: 'roles', tier: 3, name: 'Rol: Constructor', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'violet', summary: 'Rango temporal para quienes quieren identificarse como Constructor dentro de la comunidad.', includes: ['Prefijo secundario [⚒ CONSTRUCTOR] en el chat', 'Rango Constructor por 30 días', 'Acceso al permiso interno del rol Constructor', 'No incluye kit ni ítems automáticos'] },
    { id: 'lenador', category: 'roles', tier: 3, name: 'Rol: Leñador', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'ember', summary: 'Rango temporal para quienes quieren identificarse como Leñador dentro de la comunidad.', includes: ['Prefijo secundario [🪓 LEÑADOR] en el chat', 'Rango Leñador por 30 días', 'Acceso al permiso interno del rol Leñador', 'No incluye kit ni ítems automáticos'] },
    { id: 'alquimista', category: 'roles', tier: 3, name: 'Rol: Alquimista', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'cyan', summary: 'Rango temporal para quienes quieren identificarse como Alquimista dentro de la comunidad.', includes: ['Prefijo secundario [🧪 ALQUIMISTA] en el chat', 'Rango Alquimista por 30 días', 'Acceso al permiso interno del rol Alquimista', 'No incluye kit ni ítems automáticos'] },
    { id: 'nomada', category: 'roles', tier: 3, name: 'Rol: Nómada', badge: '30 días', clp: 2990, usd: 2.99, featured: false, accent: 'pink', summary: 'Rango temporal para quienes quieren identificarse como Nómada dentro de la comunidad.', includes: ['Prefijo secundario [⛺ NÓMADA] en el chat', 'Rango Nómada por 30 días', 'Acceso al permiso interno del rol Nómada', 'No incluye kit ni ítems automáticos'] },

    { id: 'kit-hermes', category: 'kits', tier: 3, name: 'Kit Hermes', badge: 'Movilidad', clp: 5990, usd: 5.99, featured: true, accent: 'violet', summary: 'Equipo de netherita de Hermes, entregado automáticamente por Odysseia.', includes: ['Set de netherita Hermes con herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '16 manzanas doradas, 16 perlas de ender y 3 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'kit-zeus', category: 'kits', tier: 7, name: 'Kit Zeus', badge: 'Mítico', clp: 14990, usd: 14.99, featured: true, accent: 'gold', summary: 'Equipo de netherita Zeus, entregado automáticamente por Odysseia.', includes: ['Set de netherita Zeus, herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '64 manzanas doradas, 64 perlas de ender y 8 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'protection-177', category: 'protection', tier: 4, name: 'Protección 177x177', badge: 'Base seria', clp: 3990, usd: 3.99, featured: false, accent: 'ember', summary: 'Hito de ProtecciónStones de 177x177 para bases y templos medianos.', includes: ['Un Hito VIP Hefesto con área final de 177x177 bloques', 'Entrega automática al conectarte, con espacio libre en inventario', 'Pensada para farms y almacenes técnicos', 'No añade un rango VIP ni aumenta el límite de regiones'] },
    { id: 'protection-481', category: 'protection', tier: 7, name: 'Protección 481x481', badge: 'En revisión', clp: 11990, usd: 11.99, featured: true, accent: 'gold', summary: 'Producto bloqueado hasta corregir la diferencia entre el tamaño vendido y la protección real del servidor.', includes: ['Checkout deshabilitado temporalmente', 'No se automatiza en Odysseia', 'Requiere decisión comercial antes de venderse', 'No se entregará un beneficio distinto al anunciado'] },

    { id: 'utility-economy', category: 'utility', tier: 6, name: 'Economía Premium', badge: 'Perks', clp: 6990, usd: 6.99, featured: false, accent: 'pink', summary: 'Beneficios comerciales permanentes configurados mediante LuckPerms.', includes: ['No modifica los límites de tiendas QuickShop', 'Color y formato de chat', 'Prefijo de Economía Premium', 'No incluye dinero, kit ni soporte prioritario automático'] },
    { id: 'dragmas-saco', category: 'utility', tier: 3, name: 'Saco de Dragmas (50.000 ₯)', badge: 'Comercio', clp: 1990, usd: 1.99, featured: false, accent: 'bronze', summary: 'Un saco mediano de dragmas de plata para impulsar tu economía.', includes: ['50.000 Dragmas (₯) depositados en el juego', 'Comercio instantáneo en tiendas de jugadores', 'Ideal para compra de materias primas', 'Entrega automatizada vía comando o ticket'] },
    { id: 'dragmas-cofre', category: 'utility', tier: 5, name: 'Cofre de Dragmas (250.000 ₯)', badge: 'Popular', clp: 7990, usd: 7.99, featured: true, accent: 'violet', summary: 'Cofre robusto de dragmas para proyectos que necesitan capital inmediato.', includes: ['250.000 Dragmas (₯) depositados en el juego', 'Mayor capital para comprar claims o máquinas', 'Entrega automatizada vía Odysseia'] },
    { id: 'dragmas-anfora', category: 'utility', tier: 7, name: 'Ánfora de Dragmas (1.000.000 ₯)', badge: 'Olimpo', clp: 24990, usd: 24.99, featured: true, accent: 'gold', summary: 'Capital para proyectos grandes, comercio pesado y compras de alto nivel.', includes: ['1.000.000 Dragmas (₯) depositados en el juego', 'Máximo poder adquisitivo en el servidor', 'Entrega automatizada vía Odysseia'] },
    { id: 'sfmaster-1h', category: 'custom', tier: 6, name: 'Pase SFMaster (1 Hora)', badge: 'Especial', clp: 5000, usd: 4.99, featured: true, accent: 'violet', summary: 'Acceso temporal, personal y controlado a la Cheat Sheet de Slimefun para trabajo técnico.', includes: ['Rango SFMaster durante 60 minutos cronológicos desde la entrega', 'Recibes la guía/libro SF Cheat; no se habilita el comando libre /sf cheat', 'Máximo 12 reclamaciones por cada ventana de 60 minutos', 'Cada ítem reclamado queda marcado a tu identidad: no se puede tirar, intercambiar, subastar, guardar para traspasarlo ni vender', 'Bloqueados Supreme e InfinityExpansion, armas, herramientas, armaduras, arcos, tridentes, elytras y equipo equivalente', 'También se bloquean diamantes, esmeraldas, netherite y ancient debris', 'Al vencer el pase se retira el rango y la guía deja de poder usarse; los ítems marcados no pasan a ser comerciables', 'El staff conserva acceso sin estas restricciones para operación y pruebas'] },
    { id: 'sfmaster-24h', category: 'custom', tier: 7, name: 'Pase SFMaster (24 Horas)', badge: 'Especial', clp: 20000, usd: 19.99, featured: true, accent: 'gold', summary: 'Acceso temporal, personal y controlado a la Cheat Sheet de Slimefun para trabajo técnico extendido.', includes: ['Rango SFMaster durante 24 horas cronológicas desde la entrega', 'Recibes la guía/libro SF Cheat; no se habilita el comando libre /sf cheat', 'Máximo 12 reclamaciones por cada ventana de 60 minutos', 'Cada ítem reclamado queda marcado a tu identidad: no se puede tirar, intercambiar, subastar, guardar para traspasarlo ni vender', 'Bloqueados Supreme e InfinityExpansion, armas, herramientas, armaduras, arcos, tridentes, elytras y equipo equivalente', 'También se bloquean diamantes, esmeraldas, netherite y ancient debris', 'Al vencer el pase se retira el rango y la guía deja de poder usarse; los ítems marcados no pasan a ser comerciables', 'El staff conserva acceso sin estas restricciones para operación y pruebas'] },

  ]
};
