/**
 * Public storefront catalog. Tebex package IDs live in server.js because they are
 * delivery infrastructure, not product copy. Keep product ids stable.
 */
export const storeCatalog = {
  updatedAt: '2026-08-08',
  currency: 'CLP',
  payment: {
    mode: 'tebex',
    discord: 'https://discord.gg/rv3vtXZTk7',
    checkout: 'https://pay.tebex.io'
  },
  categories: [
    { id: 'monthly', label: 'Pases VIP', tagline: 'Pases manuales de 30 días, sin renovación automática. Progresión griega real, utilidades y auras integradas por Odysseia.' },
    { id: 'titans', label: 'Titanes Primordiales', tagline: 'La línea superior de rangos mensuales: equipo, protecciones y habilidades de escala primordial.' },
    { id: 'roles', label: 'Roles de Juego', tagline: 'Pases manuales de 30 días, sin renovación automática. Subrangos con identidad propia dentro de la comunidad.' },
    { id: 'kits', label: 'Kits y equipo', tagline: 'Resumen de lo que trae cada línea de rango.' },
    { id: 'protection', label: 'Protecciones', tagline: 'Territorio VIP para bases, gremios y proyectos.' },
    { id: 'utility', label: 'Utilidad', tagline: 'Dragmas de plata y beneficios de economía.' },
    { id: 'slimefun', label: 'Conocimiento Slimefun', tagline: 'Desbloqueos permanentes de investigación sin entregar objetos ni permisos de administración.' }
  ],
  products: [
    { id: 'hercules', category: 'monthly', tier: 1, name: 'Hércules', badge: 'Entrada VIP', clp: 4990, usd: 4.99, featured: false, accent: 'bronze', summary: 'El punto de partida VIP para entrar fuerte al survival sin romper el balance del servidor.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Hércules', 'Incluye 1 Hito Hércules para crear una protección de 49x49 bloques', '3 homes, 5 warps de jugador (/pw) y hasta 20 tiendas QuickShop', 'Kit Hércules automático: set de diamante, herramientas, escudo y consumibles', 'Aura de armadura Odysseia con set completo de diamante: Velocidad I + Resistencia I', 'Entrega automática del kit Hércules, 1 Hito PS y $35.000 ₯ en Dragmas'] },
    { id: 'hestia', category: 'monthly', tier: 2, name: 'Hestia', badge: 'Social', clp: 7990, usd: 7.99, featured: false, accent: 'rose', summary: 'Comodidad social, mejor defensa y una economía temprana bastante más sólida.', includes: ['Pase manual de 30 días, sin renovación automática, hereda Hércules y suma Hito VIP Hestia', 'Incluye 1 Hito Hestia para crear una protección de 81x81 bloques', '5 homes, /nick, /ptime, /pweather, /ext y hasta 30 tiendas QuickShop', 'Kit Hestia automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🔥 Caminar en Lava (sustentación sobre lagos de lava, inmunidad al fuego y estela de llamas sagradas)', 'Aura de armadura Odysseia: Velocidad II + Health Boost I + Saturación', 'Entrega automática del kit Hestia, 1 Hito PS y $75.000 ₯ en Dragmas'] },
    { id: 'hermes', category: 'monthly', tier: 3, name: 'Hermes', badge: 'Recomendado', clp: 10990, usd: 10.99, featured: true, accent: 'violet', summary: 'El rango recomendado para jugar survival intensivo con movilidad real y mucha calidad de vida.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Hermes', 'Incluye 1 Hito Hermes para crear una protección de 113x113 bloques', '6 homes, 8 warps, /fly, /speed, /back, /workbench, /enderchest, /compass, /wild y hasta 40 tiendas QuickShop', 'Kit Hermes automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🪽 Paso Ligero del Viento (estela de nubes, salto alado y sin romper cultivos)', 'Aura de armadura Odysseia: Velocidad IV + Health Boost I + Saturación', 'Entrega automática del kit Hermes, 1 Hito PS y $150.000 ₯ en Dragmas'] },
    { id: 'hefesto', category: 'monthly', tier: 4, name: 'Hefesto', badge: 'Técnico', clp: 15990, usd: 15.99, featured: false, accent: 'ember', summary: 'Pensado para granjas, minería pesada y jugadores técnicos que quieren herramientas reales.', includes: ['Pase manual de 30 días, sin renovación automática, hereda anteriores y suma Hito VIP Hefesto', 'Incluye 1 Hito Hefesto para crear una protección de 177x177 bloques', '8 homes, 8 warps, /feed, /condense, estaciones virtuales completas y hasta 50 tiendas QuickShop', 'Kit Hefesto automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 🔨 Paso Ígneo de la Forja (caminar en lava sin quemarse + forja virtual)', 'Aura de armadura Odysseia: Velocidad II + Health Boost II + Resistencia al Fuego + Saturación', 'Entrega automática del kit Hefesto, 1 Hito PS y $250.000 ₯ en Dragmas'] },
    { id: 'artemisa', category: 'monthly', tier: 5, name: 'Artemisa', badge: 'Exploración', clp: 22990, usd: 22.99, featured: false, accent: 'cyan', summary: 'Verticalidad, daño a distancia y supervivencia de alto nivel para dominar mapas y combates largos.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Artemisa', 'Incluye 1 Hito Artemisa para crear una protección de 241x241 bloques', '10 homes, 12 warps de jugador, /jump, conservación de XP al morir y hasta 60 tiendas QuickShop', 'Kit Artemisa automático: set de netherita, arco, herramientas y consumibles', 'Aura de armadura Odysseia: Velocidad III + Health Boost II + Fuerza I + Saturación', 'Entrega automática del kit Artemisa, 1 Hito PS y $450.000 ₯ en Dragmas'] },
    { id: 'afrodita', category: 'monthly', tier: 6, name: 'Afrodita', badge: 'Economía', clp: 31990, usd: 31.99, featured: false, accent: 'pink', summary: 'El rango de comercio alto: acelera la economía y mantiene una presencia premium constante.', includes: ['Pase manual de 30 días, sin renovación automática, rango temporal y Hito VIP Afrodita', 'Incluye 1 Hito Afrodita para crear una protección de 353x353 bloques', '12 homes, 15 warps, /repair, /sell y hasta 70 tiendas QuickShop', 'Kit Afrodita automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: 💖 Gracia Marina (caminar sobre el agua + Dolphin\'s Grace)', 'Aura de armadura Odysseia: Velocidad III + Health Boost III + Fuerza I + Regeneración I + Saturación', 'Entrega automática del kit Afrodita, 1 Hito PS y $700.000 ₯ en Dragmas'] },
    { id: 'zeus', category: 'monthly', tier: 7, name: 'Zeus', badge: 'Rango top', clp: 44990, usd: 44.99, featured: true, accent: 'gold', summary: 'La cima del Olimpo: utilidades máximas, aura más fuerte y el kit más alto que hoy existe en DrakesCraft.', includes: ['Pase manual de 30 días, sin renovación automática y herencia total de la línea VIP anterior', 'Incluye 1 Hito Zeus para crear una protección de 481x481 bloques', '20 homes, 25 warps, /repair all, /heal, /near, keep inventory y hasta 80 tiendas QuickShop', 'Kit Zeus automático: set de netherita, herramientas, escudo y consumibles', 'Habilidad de Armadura: ⚡ Paso del Trueno (estelas de chispas eléctricas, velocidad y keep inventory)', 'Aura de armadura Odysseia: Velocidad IV + Health Boost IV + Fuerza II + Resistencia I + Saturación', 'Entrega automática del kit Zeus, 1 Hito PS y $1.500.000 ₯ en Dragmas'] },

    { id: 'thor', category: 'monthly', tier: 8, name: 'Thor', badge: 'Disponible', clp: 49990, usd: 49.99, featured: false, accent: 'gold', purchaseAvailable: true, summary: 'Panteon nordico: vuelo, el martillo Mjolnir bumerang y el Santuario del Trueno.', includes: ['Pase manual de 30 dias, sin renovacion automatica', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Trueno del Norte: <code>thunder IV</code> y <code>rage III</code> en las armas', 'Habilidad de arma con clic derecho: Martillo Mjolnir bumerán que impacta y regresa', 'Hito de proteccion de 601×601 bloques en el Survival', 'Isla de 280×280 en SkyBlock y OneBlock, se aplica al reconectar', '2.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'anubis', category: 'monthly', tier: 9, name: 'Anubis', badge: 'Disponible', clp: 54990, usd: 54.99, featured: false, accent: 'violet', purchaseAvailable: true, summary: 'Panteon egipcio: robo de vida necrotico, invocacion de espectros y la Necropolis Sagrada.', includes: ['Pase manual de 30 dias, sin renovacion automatica', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Juicio del Desierto: <code>vampire IV</code>, <code>wither III</code> y <code>decapitator III</code>', 'Habilidad de arma con clic derecho: Robo de vida necrótico e invocación de espectros', 'Hito de proteccion de 721×721 bloques en el Survival', 'Isla de 310×310 en SkyBlock y OneBlock, se aplica al reconectar', '2.500.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'poseidon', category: 'monthly', tier: 10, name: 'Poseidon', badge: 'Disponible', clp: 59990, usd: 59.99, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Panteon marino: impulso acuatico abisal y el Dominio del Oceano.', includes: ['Pase manual de 30 dias, sin renovacion automatica', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Habilidad de Armadura: 🌊 Caminar en Agua (correr sobre océanos y ríos sin hundirse, Dolphin\'s Grace y estelas de agua)', 'Marea Abisal: <code>ice_aspect IV</code> y <code>cold_steel III</code>', 'Habilidad de arma con clic derecho: Impulso acuático abisal', 'Hito de proteccion de 841×841 bloques en el Survival', 'Isla de 340×340 en SkyBlock y OneBlock, se aplica al reconectar', '3.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-japeto', category: 'titans', tier: 11, name: 'Titán Japeto', badge: 'Disponible', clp: 49990, usd: 49.99, featured: false, accent: 'ember', purchaseAvailable: true, summary: 'El primer Titán Primordial. Multiplicador 5x de favor divino.', includes: ['Pase mensual de 30 días, sin renovación automática', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Forja Primordial: <code>veinminer IV</code>, <code>blast_mining IV</code>, <code>smelter III</code>', 'Habilidad de arma con clic derecho: multiplicador ×5 de favor divino', 'Hito de protección de 1001×1001 bloques en el Survival', 'Isla de 400×400 en SkyBlock y OneBlock, se aplica al reconectar', '4.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-oceanus', category: 'titans', tier: 12, name: 'Titán Oceanus', badge: 'Disponible', clp: 59990, usd: 59.99, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Titán de las mareas: crea un Vórtice Abisal que atrae a las hordas al centro.', includes: ['Pase mensual de 30 días, sin renovación automática', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Habilidad de Armadura: 🌊 Caminar en Agua (correr sobre océanos y lagos sin hundirse con estelas abisales)', 'Corriente Eterna: <code>silk_chest</code>, <code>thrifty IV</code>, <code>veinminer V</code>', 'Habilidad de arma con clic derecho: Vórtice Abisal que atrae a las hordas al centro', 'Hito de protección de 1301×1301 bloques en el Survival', 'Isla de 450×450 en SkyBlock y OneBlock, se aplica al reconectar', '5.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-hiperion', category: 'titans', tier: 13, name: 'Titán Hiperión', badge: 'Disponible', clp: 69990, usd: 69.99, featured: false, accent: 'gold', purchaseAvailable: true, summary: 'Titán de la luz solar: rayo solar y regeneración bajo el sol.', includes: ['Pase mensual de 30 días, sin renovación automática', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Luz Primera: <code>infernus V</code>, <code>fire_shield V</code>, <code>haste VI</code>', 'Habilidad de arma con clic derecho: rayo solar y regeneración bajo el sol', 'Hito de protección de 1601×1601 bloques en el Survival', 'Isla de 500×500 en SkyBlock y OneBlock, se aplica al reconectar', '6.500.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-cronos', category: 'titans', tier: 14, name: 'Titán Cronos', badge: 'Disponible', clp: 79990, usd: 79.99, featured: false, accent: 'violet', purchaseAvailable: true, summary: 'Titán del tiempo: Parada del Tiempo que inmoviliza a los enemigos cercanos.', includes: ['Pase mensual de 30 días, sin renovación automática', 'Kit completo de netherita irrompible y soulbound: armadura, espada, mazo, pico, hacha y pala', 'Señor del Tiempo: <code>paralyze V</code>, <code>stopping_force V</code>, <code>exhaust IV</code>', 'Habilidad de arma con clic derecho: Parada del Tiempo que inmoviliza a los enemigos', 'Hito de protección de 2001×2001 bloques en el Survival', 'Isla de 550×550 en SkyBlock y OneBlock, se aplica al reconectar', '8.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'titan-caos', category: 'titans', tier: 15, name: 'Titán Caos', badge: 'Rango máximo', clp: 89990, usd: 89.99, featured: true, accent: 'rose', purchaseAvailable: true, summary: 'La cima absoluta: set primordial, dominio temporal del vacío y protección máxima.', includes: ['Pase mensual de 30 días, sin renovación automática', 'Kit completo de netherita irrompible y soulbound con trim Silence de amatista', 'Origen sin Forma distribuido en todo el set y sus armas: <code>hardened X</code>, defensas elementales VI, <code>vampire VI</code>, <code>thunder VI</code>, <code>infernus VI</code> y <code>paralyze VI</code>', 'Habilidad de arma con clic derecho: Espada Voladora Autónoma que persigue y ataca sola', '<code>/ultragod</code> personal: invulnerabilidad absoluta durante 45 segundos, con 30 minutos de recarga persistente', 'Hito de protección de 2501×2501 bloques en el Survival', 'Isla de 600×600 en SkyBlock y OneBlock, se aplica al reconectar', '10.000.000 Dragmas de bienvenida', 'El rango y el kit funcionan en las tres modalidades'] },
    { id: 'minero', category: 'roles', tier: 3, name: 'Rol: Minero', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'bronze', summary: 'Arranque técnico para minería, con herramientas y suministros reales.', includes: ['Prefijo secundario [⛏ MINERO] y rango por 30 días', 'Kit único: pico Fortuna III, pala, antorchas, escaleras y comida', 'El kit se entrega al comprar; no se repite con /kit', 'No incluye vuelo ni materiales de endgame'] },
    { id: 'cazador', category: 'roles', tier: 3, name: 'Rol: Cazador', badge: '30 días + PvE', clp: 2990, usd: 2.99, featured: false, accent: 'rose', summary: 'Equipo PvE de diamante para entrar a cazar sin saltarse la progresión VIP.', includes: ['Prefijo secundario [⚔ CAZADOR] y rango por 30 días', 'Kit único: armadura de diamante Protección IV', 'Espada Sharpness V, arco Power IV, flechas y manzanas doradas', 'No incluye netherita, elytra ni ítems Slimefun'] },
    { id: 'constructor', category: 'roles', tier: 3, name: 'Rol: Constructor', badge: '30 días + vuelo', clp: 2990, usd: 2.99, featured: false, accent: 'violet', summary: 'Un impulso de construcción con bloques iniciales y vuelo temporal controlado.', includes: ['Prefijo secundario [⚒ CONSTRUCTOR] y rango por 30 días', 'Kit único: 576 bloques de construcción, andamios y hacha', 'Vuelo durante 7 días exactos desde la compra', 'No incluye WorldEdit ni permisos de staff'] },
    { id: 'lenador', category: 'roles', tier: 3, name: 'Rol: Leñador', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'ember', summary: 'Herramientas y replantación para convertir un bosque en proyecto.', includes: ['Prefijo secundario [🪓 LEÑADOR] y rango por 30 días', 'Kit único: hacha Eficiencia V, tijeras y comida', '64 retoños de roble, 64 de abeto y harina de hueso', 'No incluye fly ni automatización de árboles'] },
    { id: 'alquimista', category: 'roles', tier: 3, name: 'Rol: Alquimista', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'cyan', summary: 'El banco de ingredientes para empezar una mesa de pociones.', includes: ['Prefijo secundario [🧪 ALQUIMISTA] y rango por 30 días', 'Soporte de pociones, verrugas, polvo de blaze y 64 frascos', 'Ingredientes básicos para extender y potenciar pociones', 'No incluye brebajes de endgame ni ítems Slimefun'] },
    { id: 'nomada', category: 'roles', tier: 3, name: 'Rol: Nómada', badge: '30 días + kit', clp: 2990, usd: 2.99, featured: false, accent: 'pink', summary: 'Movilidad y supervivencia para explorar sin regalar vuelo permanente.', includes: ['Prefijo secundario [⛺ NÓMADA] y rango por 30 días', 'Botas de diamante, brújula, cama, perlas y cohetes', 'Kit único entregado al comprar', 'No incluye elytra ni teletransporte de staff'] },

    { id: 'kit-hermes', category: 'kits', tier: 3, name: 'Kit Hermes', badge: 'Movilidad', clp: 5990, usd: 5.99, featured: true, accent: 'violet', summary: 'Equipo de netherita de Hermes, entregado automáticamente por Odysseia.', includes: ['Set de netherita Hermes con herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '16 manzanas doradas, 16 perlas de ender y 3 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'kit-zeus', category: 'kits', tier: 7, name: 'Kit Zeus', badge: 'Mítico', clp: 14990, usd: 14.99, featured: true, accent: 'gold', summary: 'Equipo de netherita Zeus, entregado automáticamente por Odysseia.', includes: ['Set de netherita Zeus, herramientas y escudo', '64 zanahorias doradas y 64 filetes cocinados', '64 manzanas doradas, 64 perlas de ender y 8 tótems', 'Entrega automática al conectarte, con espacio libre en inventario'] },
    { id: 'protection-177', category: 'protection', tier: 4, name: 'Protección 177x177', badge: 'Base seria', clp: 3990, usd: 3.99, featured: false, accent: 'ember', summary: 'Hito de ProtecciónStones de 177x177 para bases y templos medianos.', includes: ['Un Hito VIP Hefesto con área final de 177x177 bloques', 'Entrega automática al conectarte, con espacio libre en inventario', 'Pensada para farms y almacenes técnicos', 'No añade un rango VIP ni aumenta el límite de regiones'] },
    { id: 'protection-nether-colossus', category: 'protection', tier: 8, name: 'Coloso del Nether 501x501', badge: 'Nether', clp: 19990, usd: 19.99, featured: false, accent: 'ember', summary: 'Territorio masivo dentro del Nether, para bases y complejos industriales completos.', includes: ['Un Hito de proteccion de 501x501 bloques en el Nether', 'Entrega automatica al conectarte, con espacio libre en inventario', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-end-colossus', category: 'protection', tier: 8, name: 'Coloso del End 501x501', badge: 'End', clp: 24990, usd: 24.99, featured: false, accent: 'violet', summary: 'Territorio masivo dentro del End, pensado para granjas de gran escala.', includes: ['Un Hito de proteccion de 501x501 bloques en el End', 'Entrega automatica al conectarte, con espacio libre en inventario', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-atlas', category: 'protection', tier: 9, name: 'Dominio de Atlas 1001x1001', badge: 'Maximo', clp: 49990, usd: 49.99, featured: true, accent: 'gold', summary: 'La proteccion mas grande del servidor: un kilometro cuadrado para ciudades y gremios.', includes: ['Un Hito de proteccion de 1001x1001 bloques en el Overworld', 'Entrega automatica al conectarte, con espacio libre en inventario', 'Ideal para proyectos comunitarios y gremios completos', 'No anade un rango VIP ni aumenta el limite de regiones'] },
    { id: 'protection-481', category: 'protection', tier: 7, name: 'Protección 481x481', badge: 'Zeus', clp: 11990, usd: 11.99, featured: true, accent: 'gold', summary: 'Hito VIP Zeus de 481x481 bloques para ciudades, granjas y proyectos grandes.', includes: ['Un Hito VIP Zeus con área final de 481x481 bloques', 'Entrega automática mediante Odysseia al conectarte', 'Pensada para ciudades y complejos técnicos', 'No añade un rango VIP ni aumenta el límite de regiones'] },

    { id: 'utility-economy', category: 'utility', tier: 6, name: 'Economía Premium', badge: 'Perks', clp: 6990, usd: 6.99, featured: false, accent: 'pink', summary: 'Beneficios comerciales permanentes configurados mediante LuckPerms.', includes: ['No modifica los límites de tiendas QuickShop', 'Color y formato de chat', 'Prefijo de Economía Premium', 'No incluye dinero, kit ni soporte prioritario automático'] },
    { id: 'dragmas-saco', category: 'utility', tier: 3, name: 'Saco de Dragmas (50.000 ₯)', badge: 'Comercio', clp: 1990, usd: 1.99, featured: false, accent: 'bronze', summary: 'Un saco mediano de dragmas de plata para impulsar tu economía.', includes: ['50.000 Dragmas (₯) depositados en el juego', 'Comercio instantáneo en tiendas de jugadores', 'Ideal para compra de materias primas', 'Entrega automatizada vía comando o ticket'] },
    { id: 'dragmas-cofre', category: 'utility', tier: 5, name: 'Cofre de Dragmas (250.000 ₯)', badge: 'Popular', clp: 7990, usd: 7.99, featured: true, accent: 'violet', summary: 'Cofre robusto de dragmas para proyectos que necesitan capital inmediato.', includes: ['250.000 Dragmas (₯) depositados en el juego', 'Mayor capital para comprar claims o máquinas', 'Entrega automatizada vía Odysseia'] },
    { id: 'dragmas-anfora', category: 'utility', tier: 7, name: 'Ánfora de Dragmas (1.000.000 ₯)', badge: 'Olimpo', clp: 24990, usd: 24.99, featured: true, accent: 'gold', summary: 'Capital para proyectos grandes, comercio pesado y compras de alto nivel.', includes: ['1.000.000 Dragmas (₯) depositados en el juego', 'Máximo poder adquisitivo en el servidor', 'Entrega automatizada vía Odysseia'] },
    { id: 'slimefun-research-all', category: 'slimefun', tier: 1, name: 'Conocimiento Total de Slimefun', badge: 'Disponible', clp: 9990, usd: 10.00, featured: false, accent: 'cyan', purchaseAvailable: true, summary: 'Desbloqueo permanente de las investigaciones actuales de Slimefun.', includes: ['No entrega objetos ni máquinas', 'No habilita el comando libre <code>/sf cheat</code>', 'Debes estar conectado para recibir la entrega', 'Las investigaciones nuevas añadidas a futuro siguen su progresión normal'] },

  ]
};
